name: CI - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository (more robustly)
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0 # Fetches all history, which can help LFS

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Manually pull LFS files (Belt and Suspenders)
      # This ensures that even if the checkout LFS step had a silent issue,
      # we try again manually before doing anything else.
      - name: Force pull Git LFS files
        run: git lfs pull

      # Step 4: DEBUG - List all files to verify
      # We absolutely need to see the output of this step.
      - name: List files in workspace
        run: ls -R

      # Step 5: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 6: Run tests
      - name: Run tests with pytest
        run: pytest